/**
 * PromptWise adapter — M2.
 *
 * Reads a `promptwise@1` package written by `scripts/promptwise-runner/run.py`
 * and shows three views of it: the four learning curves, the cost/success plane
 * the routers end up in, and one routing decision at a time with the beliefs
 * that produced it.
 *
 * The directory follows the shape `rm-r1` sets out:
 *   contract.ts  what the views may assume. Written once, then coded against.
 *   model.ts     fingerprint + normalise. Pure, and tested from plain node.
 *   Curves.tsx   V1 — utility, cost, success and OPR against t.
 *   Pareto.tsx   V2 — where each router ends: what it spent, what it solved.
 *   Replay.tsx   V3 — the step list, and the arm beliefs behind one choice.
 *   View.tsx     the tab strip, and the disclosure that holds on all three.
 *   index.ts     this file: the one object the registry is handed.
 */

import type { Adapter } from '../../types'
import { parse, sniff } from './model'
import type { PromptWiseModel } from './contract'
import { View } from './View'

export type { PromptWiseModel } from './contract'

/**
 * `name` must stay exactly `promptwise`: the landing page matches adapter names
 * against its roadmap rows, so any other name would leave the planned PromptWise
 * card sitting next to this one. It is also the name a package declares in
 * `agentlens_format` — `promptwise@1` — which is how a dropped package routes
 * here without being fingerprinted at all (`shell/sniff.ts`).
 *
 * Both demos are our own output, not a research group's: `run.py` drives the
 * upstream learners unmodified over a world it invents. So both credits say
 * "Generated by", name the synthetic part first, and point at the repository the
 * algorithms come from rather than at any source for the data — there is none.
 * Attribution in full, with the licence, is in THIRD_PARTY_NOTICES.md.
 *
 * The tiered package leads. It is the world the algorithm was written for — the
 * cheapest model is also the weakest, so paying more sometimes buys the answer —
 * and it is the one whose trace shows the escalations. The uniform package is
 * upstream's own setup, where every model succeeds about equally often and the
 * right move is to settle on the cheapest and retry it; that is a real result
 * and a poor first impression, because the mechanism the demo is about barely
 * fires. Second card, not the first.
 */
export const promptWiseAdapter: Adapter<PromptWiseModel> = {
  name: 'promptwise',
  label: 'PromptWise cost-aware routing',
  blurb:
    'Which model each prompt was sent to, when the router paid for a dearer one after a cheap one failed, and what the whole stream cost — with the beliefs behind any one of those decisions.',
  sniff,
  parse,
  View,
  demos: [
    {
      id: 'promptwise-tiered',
      label: 'PromptWise routing — models that differ in cost and in competence',
      path: 'demo-data/promptwise/tiered.json',
      credit: {
        text: "Generated by scripts/promptwise-runner/run.py — synthetic data on invented per-model success rates, running the learners of yannxiaoyanhu/PromptWise (MIT) unmodified. No figure here reproduces the paper's.",
        href: 'https://github.com/yannxiaoyanhu/PromptWise',
      },
    },
    {
      id: 'promptwise-uniform',
      label: 'PromptWise routing — every model equally likely to succeed',
      path: 'demo-data/promptwise/uniform.json',
      credit: {
        text: "Generated by scripts/promptwise-runner/run.py — synthetic data on upstream test.py's own uniform success table, running the learners of yannxiaoyanhu/PromptWise (MIT) unmodified. No figure here reproduces the paper's.",
        href: 'https://github.com/yannxiaoyanhu/PromptWise',
      },
    },
  ],
}
