/**
 * ArbiterOS adapter — M3.
 *
 * Reads the package `scripts/arbiteros-runner/run.py` writes: ArbiterOS's own
 * 105 red-team cases replayed through ArbiterOS's own policy kernel, offline —
 * no model, no gateway, no network, no cost. What comes out of that replay and
 * exists nowhere on disk is the interesting part: the propagated security
 * labels, and what the policy chain concluded about each case.
 *
 * The directory follows the shape the other adapters set out:
 *   contract.ts     what the views may assume. Written once, then coded against.
 *   model.ts        fingerprint + normalise + propagation. Pure, no React.
 *   CaseBrowser.tsx the 105 cases as one scannable index.
 *   TaintGraph.tsx  one case, instruction by instruction, and where each label
 *                   came from. No graph library — dagre went out in M0.
 *   PolicyPanel.tsx the counts, with the configuration that explains them.
 *   View.tsx        tabs between the three.
 *   index.ts        this file: the one object the registry is handed.
 *
 * ── The format tag does not match this name, and that is on purpose ──────────
 * The committed package declares `agentlens_format: "arbiteros-trace@1"`, while
 * this adapter is registered as `arbiteros` — the name the landing page matches
 * against its roadmap row, and the name the brief fixes. `shell/sniff.ts`
 * matches a declaration's name against the adapter key, so without help it would
 * report the package as handled by nobody and fall through to fingerprinting.
 * `main.tsx` therefore registers this adapter with `formatNames:
 * ['arbiteros-trace']`. That is a statement about which tags this adapter reads,
 * not a rename: `run.py` still writes `arbiteros-trace@1`, `model.test.ts` still
 * pins that literal, and neither had to move.
 */

import type { Adapter } from '../../types'
import { parse, sniff } from './model'
import type { ArbiterosModel } from './contract'
import { View } from './View'

export type { ArbiterosModel } from './contract'

/**
 * `name` must stay exactly `arbiteros`: `App.tsx` matches adapter names against
 * its roadmap rows, so any other spelling would leave the M3 row advertised as
 * unbuilt beside the card that opens it — and would make `arbiteros-preview`
 * look like a preview of nothing.
 *
 * The blurb carries the pair rather than either number alone. It is the sentence
 * a visiting PI reads first, and it is the sentence most likely to be
 * screenshotted away from everything that qualifies it: "1 of 105 intercepted"
 * on its own would tell Qiang Xu that his red-team suite stops one attack, which
 * is false. It leads with 39 rather than the larger 87, for the reason spelled
 * out at `hasRefusal` in `model.ts` — 87 counts a field the kernel fills in
 * itself — and it carries the safe/unsafe split, because a 47% hit rate quoted
 * without the 30% false-positive rate beside it is the more flattering half of
 * one result. `PolicyPanel` says the same thing at length, with the
 * configuration and the per-policy table behind it.
 *
 * The credit says AgentLens generated this data, because AgentLens did — the
 * cases, the kernel and the policy names are upstream's, but the replay that
 * produced the labels and verdicts is ours, and `types.ts` asks for "Generated
 * by <x>" in exactly that situation. Full attribution and the licence are in
 * THIRD_PARTY_NOTICES.md.
 */
export const arbiterosAdapter: Adapter<ArbiterosModel> = {
  name: 'arbiteros',
  label: 'ArbiterOS policy replay',
  blurb:
    "All 105 red-team cases replayed through ArbiterOS's own policy kernel, offline and with no model called: a policy composes a refusal on 39 of them — 21 of the 45 labelled unsafe, 18 of the 60 labelled safe — while the shipped registry lets the kernel act on 1, and every instruction's security labels are traced back to the step that introduced them.",
  sniff,
  parse,
  View,
  demos: [
    {
      id: 'arbiteros',
      // The label names the artifact and counts it: this is the replay, not the
      // case files (`arbiteros-preview` opens those), and it is the whole suite
      // rather than a selection from it. Both counts are the package's own,
      // recomputed from its records by `parse()`.
      label: 'ArbiterOS policy replay · all 105 red-team cases, 500 instructions',
      path: 'demo-data/arbiteros/traces.json',
      credit: {
        text: "Generated by AgentLens: the 105 red-team cases and the policy kernel are cure-lab/ArbiterOS, Apache-2.0, replayed unmodified and offline — no model was called, so every label and verdict here was computed by that kernel rather than written by an LLM",
        href: 'https://github.com/cure-lab/ArbiterOS',
      },
    },
  ],
}
